//Console.WriteLine("Enter first number");
//int x = int.Parse(Console.ReadLine());
//Console.WriteLine("enter the second number");
//int y = int.Parse(Console.ReadLine());
//Console.WriteLine("The result is: ");
//Console.WriteLine(x + y);
//Console.WriteLine(x - y);
//Console.WriteLine(x * y);
//Console.WriteLine(x / y);
Console.WriteLine("enter the first number");
double x = double.Parse(Console.ReadLine());
Console.WriteLine("enter the second nummber");
double y = double.Parse(Console.ReadLine());
Console.BackgroundColor = ConsoleColor.Red;
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine("the result is:  ");
Console.WriteLine(x + y);
